server.port=8081

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:file:./data/filedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=uploads

# JWT
jwt.secret=cloudfile-management-super-secret-jwt-key-ashutosh-2026
jwt.expiration=86400000
